{
 "name": "StorageSyncInnerErrorDetails",
 "fields": [
  {
   "containsDiscriminatedTypeValue": false,
   "jsonName": "callStack",
   "name": "CallStack",
   "objectDefinition": {
    "type": "String",
    "referenceName": null
   },
   "optional": true,
   "required": false,
   "description": "Call stack of the error."
  },
  {
   "containsDiscriminatedTypeValue": false,
   "jsonName": "innerException",
   "name": "InnerException",
   "objectDefinition": {
    "type": "String",
    "referenceName": null
   },
   "optional": true,
   "required": false,
   "description": "Exception of the inner error."
  },
  {
   "containsDiscriminatedTypeValue": false,
   "jsonName": "innerExceptionCallStack",
   "name": "InnerExceptionCallStack",
   "objectDefinition": {
    "type": "String",
    "referenceName": null
   },
   "optional": true,
   "required": false,
   "description": "Call stack of the inner error."
  },
  {
   "containsDiscriminatedTypeValue": false,
   "jsonName": "message",
   "name": "Message",
   "objectDefinition": {
    "type": "String",
    "referenceName": null
   },
   "optional": true,
   "required": false,
   "description": "Error message of the error."
  }
 ]
}